import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BadgeCheck, CalendarDays, Check, Factory, Gauge, Leaf, MapPin, Menu, MessageCircle, Phone, ShieldCheck, Sparkles, Wrench, X } from 'lucide-react';
import './styles.css';
import './overrides.css';
import './logo.css';

const nav=[['Home','होम','home'],['About','हमारे बारे में','about'],['Products','उत्पाद','products'],['Gallery & News','गैलरी और समाचार','gallery'],['Contact','संपर्क','contact']];
const languages=[
  ['en','English'],['pa','ਪੰਜਾਬੀ'],['hi','हिन्दी'],['as','অসমীয়া'],['bn','বাংলা'],['brx','बड़ो'],
  ['doi','डोगरी'],['gu','ગુજરાતી'],['kn','ಕನ್ನಡ'],['ks','کٲشُر'],['gom','कोंकणी'],['mai','मैथिली'],
  ['ml','മലയാളം'],['mni-Mtei','ꯃꯤꯇꯩꯂꯣꯟ'],['mr','मराठी'],['ne','नेपाली'],['or','ଓଡ଼ିଆ'],
  ['sa','संस्कृतम्'],['sat','ᱥᱟᱱᱛᱟᱲᱤ'],['sd','سنڌي'],['ta','தமிழ்'],['te','తెలుగు'],['ur','اردو']
];
const copy={
en:{heroTag:'Power for work. Machines for growth.',heroTitle:'Built to keep India moving.',heroText:'Generators and chaff cutters made for demanding days.',explore:'Explore products',quote:'Get a quote',made:'Made in India',tested:'Quality checked',service:'Service support',products:'What we make',productsSub:'Two product families. One dependable name.',gen:'Generators',genText:'Reliable power for farms, businesses and industry.',chaff:'Chaff cutters',chaffText:'Fast, consistent fodder preparation for every farm size.',view:'View range',why:"Why F.C. DOD's",whyTitle:'Built around your work',whyText:'Simple to operate. Easy to service. Ready for the field.',p1:'Performance first',p1t:'Built for dependable, everyday output.',p2:'Checked before dispatch',p2t:'Every machine inspected before it leaves.',p3:'Made for Indian conditions',p3t:'Practical machinery for real working environments.'},
hi:{heroTag:'काम के लिए शक्ति। विकास के लिए मशीनें।',heroTitle:'भारत को आगे बढ़ाने के लिए निर्मित।',heroText:'कठिन काम के लिए भरोसेमंद जनरेटर और चारा काटने की मशीनें।',explore:'उत्पाद देखें',quote:'कीमत पूछें',made:'भारत में निर्मित',tested:'गुणवत्ता जाँची गई',service:'सर्विस सहायता',products:'हम क्या बनाते हैं',productsSub:'दो उत्पाद श्रेणियाँ। एक भरोसेमंद नाम।',gen:'जनरेटर',genText:'खेत, व्यापार और उद्योग के लिए भरोसेमंद बिजली।',chaff:'चारा काटने की मशीन',chaffText:'हर आकार के पशुपालक के लिए तेज़ और समान कटाई।',view:'पूरी रेंज देखें',why:"F.C. DOD's क्यों",whyTitle:'आपके काम को ध्यान में रखकर निर्मित',whyText:'चलाने में आसान। सर्विस में सरल। खेत के लिए तैयार।',p1:'प्रदर्शन पहले',p1t:'हर दिन भरोसेमंद काम के लिए निर्मित।',p2:'डिस्पैच से पहले जाँच',p2t:'हर मशीन भेजने से पहले जाँची जाती है।',p3:'भारतीय परिस्थितियों के लिए',p3t:'असली कार्य परिस्थितियों के लिए व्यावहारिक मशीनें।'}};

function go(page){window.location.hash=page==='home'?'#/':`#/${page}`;window.scrollTo({top:0,behavior:'smooth'});}
function Logo(){return <button className="logo" onClick={()=>go('home')} aria-label="F.C. DOD's home"><img src="./fcdods-logo.jpg" alt="F.C. DOD's — established 1978, ISO 9001:2015 certified"/></button>;}
function Header({page}){
  const[open,setOpen]=useState(false);
  useEffect(()=>{
    window.googleTranslateElementInit=()=>new window.google.translate.TranslateElement({pageLanguage:'en',includedLanguages:languages.map(([code])=>code).join(','),autoDisplay:false},'google_translate_element');
    if(!document.querySelector('script[data-fcdods-translate]')){const script=document.createElement('script');script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';script.async=true;script.dataset.fcdodsTranslate='true';document.body.appendChild(script);}
  },[]);
  const changeLanguage=(code)=>{const apply=()=>{const combo=document.querySelector('.goog-te-combo');if(!combo)return false;combo.value=code;combo.dispatchEvent(new Event('change',{bubbles:true}));return true;};if(!apply())setTimeout(apply,800);};
  return <header className="site-header"><div id="google_translate_element" aria-hidden="true"/><div className="site-width header-inner"><Logo/><nav className={open?'nav-open':''}>{nav.map(([en,,id])=><button className={page===id?'active':''} key={id} onClick={()=>{go(id);setOpen(false);}}>{en}</button>)}<a className="header-call" href="tel:+919216362163"><Phone size={16}/>Call us</a></nav><div className="header-actions"><label className="language-label"><span>Language</span><select defaultValue="en" onChange={e=>changeLanguage(e.target.value)} aria-label="Choose website language">{languages.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><button className="menu-button" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div></div></header>;
}
function Footer(){return <footer className="site-footer"><div className="site-width footer-grid"><Logo/><p>Generators and agricultural machinery,<br/>made for work that matters.</p><div className="footer-links">{nav.slice(1).map(([label,,id])=><button key={id} onClick={()=>go(id)}>{label}</button>)}</div></div><div className="site-width footer-bottom"><span>© 2026 F.C. DOD&apos;s</span><span>Made in India</span></div></footer>;}
function WhatsApp(){return <a className="whatsapp" href="https://wa.me/919216362163?text=Hello%20F.C.%20DOD%27s%2C%20I%20want%20to%20know%20more%20about%20your%20products." target="_blank" rel="noreferrer"><MessageCircle/><span>WhatsApp</span></a>;}

function Home({lang}){const t=copy[lang];return <><section className="hero"><div className="hero-image"/><div className="hero-shade"/><div className="site-width hero-inner"><div className="hero-copy"><div className="eyebrow"><span/>{t.heroTag}</div><h1>{t.heroTitle}</h1><p>{t.heroText}</p><div className="hero-actions"><button className="button button-primary" onClick={()=>go('products')}>{t.explore}<ArrowRight size={18}/></button><button className="button button-light" onClick={()=>go('contact')}>{t.quote}</button></div></div></div><div className="hero-rail site-width"><span><Factory size={17}/>{t.made}</span><span><ShieldCheck size={17}/>{t.tested}</span><span><Wrench size={17}/>{t.service}</span></div></section><section className="section site-width"><div className="section-heading"><div><span className="kicker">Products</span><h2>{t.products}</h2></div><p>{t.productsSub}</p></div><div className="product-grid"><button className="product-tile" onClick={()=>go('products')}><div className="product-image product-image-generator"/><div className="product-overlay"/><div className="product-content"><span>01</span><h3>{t.gen}</h3><p>{t.genText}</p><b>{t.view}<ArrowRight size={18}/></b></div></button><button className="product-tile" onClick={()=>go('products')}><div className="product-image product-image-chaff"/><div className="product-overlay"/><div className="product-content"><span>02</span><h3>{t.chaff}</h3><p>{t.chaffText}</p><b>{t.view}<ArrowRight size={18}/></b></div></button></div></section><section className="trust-band"><div className="site-width trust-grid"><div><span className="kicker kicker-light">{t.why}</span><h2>{t.whyTitle}</h2><p>{t.whyText}</p></div><div className="trust-points"><article><Gauge/><h3>{t.p1}</h3><p>{t.p1t}</p></article><article><BadgeCheck/><h3>{t.p2}</h3><p>{t.p2t}</p></article><article><Leaf/><h3>{t.p3}</h3><p>{t.p3t}</p></article></div></div></section></>;}
function PageHero({kicker,title,text,image='factory-team.jpg'}){return <section className="page-hero"><img src={`./${image}`} alt=""/><div className="page-hero-shade"/><div className="site-width"><span className="kicker kicker-light">{kicker}</span><h1>{title}</h1><p>{text}</p></div></section>;}
function About(){return <><PageHero kicker="Our company" title="Built with purpose." text="A manufacturing story shaped by useful machines and long-term relationships."/><section className="section site-width about-grid"><div><span className="kicker">Who we are</span><h2>Practical engineering. Personal responsibility.</h2></div><div className="body-copy"><p>F.C. DOD&apos;s manufactures generators and chaff cutters for customers who need reliable equipment and straightforward support.</p><p className="content-note">Replace this paragraph with your real company history, manufacturing location, years in business and quality certifications.</p><div className="mini-values"><span><Factory/>Own manufacturing</span><span><Wrench/>Service focused</span><span><BadgeCheck/>Quality minded</span></div></div></section><section className="founder-section"><div className="site-width founder-grid"><div className="founder-placeholder"><span>Founder photograph</span></div><div><span className="kicker">Founder</span><h2>Meet the person behind the machines.</h2><h3>Founder name</h3><p>Add a short, genuine story about why the company was started, the founder&apos;s experience, and the values that still guide the team.</p><blockquote>“Add a short founder quote here.”</blockquote></div></div></section></>;}
const gens=['Portable / compact','Silent canopy','Commercial backup','Industrial power'];const cutters=['Manual','Electric motor','Engine driven','Heavy-duty farm'];
function Products(){return <><PageHero kicker="Product range" title="Machines that deliver." text="Choose a category. We will help you match the right model to your work." image="hero-machinery.png"/><section className="section site-width"><div className="range-block"><div className="range-image generator-crop"><span>Generator range</span></div><div><span className="kicker">Generators</span><h2>Power you can count on.</h2><p>For farms, shops, institutions, construction and industry.</p><ul>{gens.map(x=><li key={x}><Check/>{x}</li>)}</ul><button className="button button-primary" onClick={()=>go('contact')}>Ask for catalogue<ArrowRight size={18}/></button></div></div><div className="range-block reverse"><div className="range-image chaff-photo"><span>Chaff cutter range</span></div><div><span className="kicker">Chaff cutters</span><h2>Faster fodder preparation.</h2><p>Built for dairy farms, livestock owners and feed operations.</p><ul>{cutters.map(x=><li key={x}><Check/>{x}</li>)}</ul><button className="button button-primary" onClick={()=>go('contact')}>Ask for catalogue<ArrowRight size={18}/></button></div></div></section><section className="spec-prompt"><div className="site-width"><Sparkles/><div><h2>Add model specifications</h2><p>Share model names, output, fuel type, power, capacity, dimensions, warranty and product photos. We&apos;ll turn them into clear comparison cards.</p></div></div></section></>;}
function Gallery(){const cards=[['factory-team.jpg','Inside our works','Manufacturing'],['chaff-field.jpg','At work on the farm','Product in use'],['hero-machinery.png','Power and agriculture','Product range'],['factory-team.jpg','Quality check before dispatch','Workshop'],['chaff-field.jpg','Made for daily farm work','Field story'],['hero-machinery.png',"F.C. DOD's machines",'Company']];return <><PageHero kicker="Gallery · News · Events" title="From our floor to the field." text="See the machines, the people and the moments behind our work." image="chaff-field.jpg"/><section className="section site-width"><div className="gallery-grid">{cards.map(([img,title,tag],i)=><figure className={i===0||i===5?'wide':''} key={i}><img src={`./${img}`} alt={title}/><figcaption><span>{tag}</span><h3>{title}</h3></figcaption></figure>)}</div></section><section className="news-section"><div className="site-width"><div className="section-heading"><div><span className="kicker">Latest</span><h2>News & events</h2></div><p>Add exhibitions, dealer meets, deliveries and company updates here.</p></div><div className="news-grid">{['Upcoming exhibition','Dealer meet','New product launch'].map((x,i)=><article key={x}><CalendarDays/><span>{i===0?'UPCOMING':'UPDATE'}</span><h3>{x}</h3><p>Date and event details to be added.</p></article>)}</div></div></section></>;}
function Contact(){
  const[form,setForm]=useState({name:'',phone:'',product:'Generator',city:'',message:''});
  const send=e=>{e.preventDefault();const text=`Hello F.C. DOD's,\nName: ${form.name}\nPhone: ${form.phone}\nProduct: ${form.product}\nCity: ${form.city}\nRequirement: ${form.message}`;window.open(`https://wa.me/919216362163?text=${encodeURIComponent(text)}`,'_blank');};
  return <><PageHero kicker="Contact" title="Let's talk machines." text="Tell us what you need. We will help you find the right fit." image="hero-machinery.png"/><section className="section site-width contact-grid"><div><span className="kicker">Reach us</span><h2>Sales & support</h2><p>Call, WhatsApp or visit our works in Jaito.</p><div className="contact-list"><a href="tel:+919216362163"><Phone/>+91 92163 62163</a><a href="https://wa.me/919216362163" target="_blank" rel="noreferrer"><MessageCircle/>WhatsApp us</a><a href="https://www.google.com/maps/search/?api=1&query=30.4409758,74.8884689" target="_blank" rel="noreferrer"><MapPin/>F.C. DOD Toka Machine, Jaitu–Bathinda Road, Jaito, Punjab 151202</a></div><div className="map-placeholder"><iframe title="F.C. DOD's location in Jaito" loading="lazy" src="https://www.google.com/maps?q=30.4409758,74.8884689&z=15&output=embed"/></div></div><form className="contact-form" onSubmit={send}><h3>Request a quote</h3><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><div className="form-row"><label>Phone<input required type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="10-digit mobile"/></label><label>Product<select value={form.product} onChange={e=>setForm({...form,product:e.target.value})}><option>Generator</option><option>Chaff cutter</option><option>Dealership</option><option>Other</option></select></label></div><label>City / State<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="Your location"/></label><label>Requirement<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Model, capacity, quantity or use case"/></label><button className="button button-primary" type="submit">Send on WhatsApp<MessageCircle size={18}/></button><small>No server needed — this opens WhatsApp with the form details.</small></form></section></>;
}
function App(){const getPage=()=>{const x=window.location.hash.replace('#/','').replace('#','');return['about','products','gallery','contact'].includes(x)?x:'home';};const[page,setPage]=useState(getPage);useEffect(()=>{const fn=()=>setPage(getPage());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);const content=useMemo(()=>({home:<Home lang="en"/>,about:<About/>,products:<Products/>,gallery:<Gallery/>,contact:<Contact/>})[page],[page]);return <><Header page={page}/><main>{content}</main><Footer/><WhatsApp/></>;}
createRoot(document.getElementById('root')).render(<App/>);
